=== rvanheest/spickle/example/src/main/resources/all/person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="persontype">
        <xs:all>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string" minOccurs="1"/>
            <xs:element name="age" type="xs:positiveInteger"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="randomnumberlist">
        <xs:list itemType="xs:integer"/>
    </xs:simpleType>


    <xs:element name="persons">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" type="persontype" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="somenumbers" type="randomnumberlist"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rvanheest/spickle/example/src/main/resources/all/person1.xml
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="person.xsd">
    <person>
        <firstname>Jan</firstname>
        <lastname>Hus</lastname>
        <age>25</age>
    </person>
    <person>
        <lastname>Luther</lastname>
        <firstname>Martin</firstname>
        <age>50</age>
    </person>
    <person>
        <age>40</age>
        <lastname>Calvin</lastname>
        <firstname>John</firstname>
    </person>
    <somenumbers>1 2 3 4 5</somenumbers>
</persons>
