=== rvanheest/spickle/example/src/main/resources/xs-choice-many/xs-choice-many.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mixed">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="e">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="a" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="a" type="xs:string"/>

                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="a" type="xs:string"/>
                    <xs:element name="b" type="xs:string"/>
                    <xs:element name="c">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="c1" type="xs:string"/>
                                <xs:element name="c2" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="d1" type="xs:string"/>
                    <xs:element name="d2">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="d2A" type="xs:string"/>
                                <xs:element name="d2B" type="xs:string" minOccurs="0"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>

                <xs:element name="f">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="a" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rvanheest/spickle/example/src/main/resources/xs-choice-many/xs-choice-many1.xml
<mixed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="xs-choice-many.xsd">
    <e>
        <a>abcdef</a>
    </e>

    <a>xyz</a>

    <!-- choice starts here -->
    <a>a-A</a>
    <b>b-A</b>
    <c>
        <c1>c-c1-A</c1>
        <c2>c-c2-A</c2>
    </c>
    <d1>d1-A</d1>
    <d2>
        <d2A>d2-d2A-A</d2A>
        <d2B>d2-d2B-A</d2B>
    </d2>
    <a>a-B</a>
    <b>b-B</b>
    <c>
        <c1>c-c1-B</c1>
        <c2>c-c2-B</c2>
    </c>
    <c>
        <c1>c-c1-C</c1>
        <c2>c-c2-C</c2>
    </c>
    <d1>d1-B</d1>
    <d2>
        <d2A>d2-d2A-B</d2A>
    </d2>
    <!-- choice ends here -->

    <f>
        <a>uvwxyz</a>
    </f>
</mixed>
